spring:
  datasource:
    url: jdbc:mysql://localhost:3306/engine_ast?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp